name: Build and Push Docker Image

on:
  push:
    branches:
      - dev_jughwan

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767397880837:role/bbanggooodserverrole
          aws-region: ap-northeast-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: springcontents
          IMAGE_TAG: latest
        run: |
          # Build Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./springcontents
          
          # Push Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Output image info
        run: echo "Docker image built and pushed: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"