# Git Action 이름 수정
name: SpringContents Build and Push Docker Image

on:
  pull_request:
    branches:
      - develop
    # 변경이 생기는 폴더명 수정
    paths:
      - 'SpringContents/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ECR_REGISTRY: 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com
      # 등록할 ECR 이름 수정
      ECR_REPOSITORY: springcontents
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767397880837:role/bbanggooodserverrole
          aws-region: ap-northeast-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build and push Docker image
        # 빌드를 진행할 폴더명 수정
        run: |
          # Build Docker image
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ./SpringContents
          
          # Push Docker image to ECR
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Output image info
        run: |
          echo "Docker image built and pushed: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"