name: Build and Push Docker Image

on:
  push:
    branches:
      - dev_jughwan

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767397880837:role/bbanggooodserverrole
          aws-region: ap-northeast-2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: SpringContents

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: SpringContents

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: springcontents
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f SpringContents/Dockerfile SpringContents
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Logout from Amazon ECR
        run: docker logout 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com