name: Build and Push View Record Docker image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'SpringViewRecord/**'

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./SpringViewRecord/gradlew

      - name: Build with Gradle
        run: ./SpringViewRecord/gradlew build -p ./SpringViewRecord

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767397880837:role/bbanggooodserverrole
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: 767397880837.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: springviewrecord
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./SpringViewRecord
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
